name: badger
description: "Badger: Notes & Todos."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  sqflite: ^2.2.6
  path: ^1.8.2
  material_color_generator: ^1.1.0
  google_fonts: ^4.0.4
  flutter_markdown: ^0.6.14
  shared_preferences: ^2.1.1
  markdown: ^7.1.0
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  
  flutter_launcher_icons: ^0.13.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
